/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import classes.Employee; //to access the necessary properties of the Employee class
import com.opencsv.exceptions.CsvValidationException;
import java.awt.Dialog;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DREAM PC
 */
public class FrmViewEmployee extends javax.swing.JDialog {
private String EmployeeNo;
    /**
     * Creates new form FrmViewEmployee
     */
   
    public FrmViewEmployee(String EmpNo) {
        setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
             initComponents();
             EmployeeNo = EmpNo;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPosition = new javax.swing.JTextField();
        lblImmediateSup = new javax.swing.JLabel();
        txtEmployeeNo = new javax.swing.JTextField();
        txtImmediateSup = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblBasicSalary = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblRiceSubsidy = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblPhoneAllowance = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblSSSNo = new javax.swing.JLabel();
        txtSSSNo = new javax.swing.JTextField();
        lblPhealthNo = new javax.swing.JLabel();
        lblClothingAllowance = new javax.swing.JLabel();
        lblgrossSemiMonthlyRate = new javax.swing.JLabel();
        lblHourlyRate = new javax.swing.JLabel();
        txtBasicSalary = new javax.swing.JTextField();
        txtPhealthNo = new javax.swing.JTextField();
        txtRiceSubsidy = new javax.swing.JTextField();
        lblTinNo = new javax.swing.JLabel();
        txtPhoneAllowance = new javax.swing.JTextField();
        txtTinNo = new javax.swing.JTextField();
        txtClothingAllowance = new javax.swing.JTextField();
        lblPagibigNo = new javax.swing.JLabel();
        txtGrossSemiMonthlyRate = new javax.swing.JTextField();
        txtPagibigNo = new javax.swing.JTextField();
        txtHourlyRate = new javax.swing.JTextField();
        lblBirthday = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblEmployeeNo = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                GetEmployeeRecord(evt);
            }
        });

        txtPosition.setEditable(false);

        lblImmediateSup.setText("Immediate Supervisor:");

        txtEmployeeNo.setEditable(false);

        txtImmediateSup.setEditable(false);

        lblLastName.setText("Last Name:");

        lblBasicSalary.setText("Basic Salary:");

        txtLastName.setEditable(false);

        lblRiceSubsidy.setText("Rice Subsidy:");

        lblFirstName.setText("First Name:");

        lblPhoneAllowance.setText("Phone Allowance:");

        txtFirstName.setEditable(false);

        lblSSSNo.setText("SSS No.:");

        txtSSSNo.setEditable(false);

        lblPhealthNo.setText("PhilHealth No.:");

        lblClothingAllowance.setText("Clothing Allowance:");

        lblgrossSemiMonthlyRate.setText("Gross Semi Monthly Rate:");

        lblHourlyRate.setText("Hourly Rate:");

        txtBasicSalary.setEditable(false);

        txtPhealthNo.setEditable(false);

        txtRiceSubsidy.setEditable(false);

        lblTinNo.setText("TIN No.:");

        txtPhoneAllowance.setEditable(false);

        txtTinNo.setEditable(false);

        txtClothingAllowance.setEditable(false);

        lblPagibigNo.setText("Pagibig No.:");

        txtGrossSemiMonthlyRate.setEditable(false);

        txtPagibigNo.setEditable(false);

        txtHourlyRate.setEditable(false);

        lblBirthday.setText("Birthday:");

        lblStatus.setText("Status:");

        txtBirthday.setEditable(false);

        txtStatus.setEditable(false);

        lblAddress.setText("Address:");

        lblPosition.setText("Position:");

        txtAddress.setEditable(false);

        lblEmployeeNo.setText("Employee No.:");

        btnClose.setText("Close");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseFrameClose(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmployeeNo)
                            .addComponent(lblLastName)
                            .addComponent(lblFirstName)
                            .addComponent(lblBirthday)
                            .addComponent(lblAddress))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmployeeNo)
                            .addComponent(txtLastName)
                            .addComponent(txtFirstName)
                            .addComponent(txtBirthday)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSSSNo)
                            .addComponent(lblPhealthNo)
                            .addComponent(lblTinNo)
                            .addComponent(lblPagibigNo))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTinNo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhealthNo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPagibigNo)
                            .addComponent(txtSSSNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addComponent(lblPosition)
                            .addComponent(lblImmediateSup)
                            .addComponent(lblBasicSalary)
                            .addComponent(lblRiceSubsidy)
                            .addComponent(lblPhoneAllowance)
                            .addComponent(lblClothingAllowance))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPosition)
                            .addComponent(txtStatus)
                            .addComponent(txtImmediateSup)
                            .addComponent(txtBasicSalary)
                            .addComponent(txtRiceSubsidy)
                            .addComponent(txtPhoneAllowance)
                            .addComponent(txtClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblgrossSemiMonthlyRate)
                            .addComponent(lblHourlyRate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGrossSemiMonthlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmployeeNo)
                            .addComponent(txtEmployeeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBirthday))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAddress)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSSSNo)
                            .addComponent(txtSSSNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhealthNo)
                            .addComponent(txtPhealthNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTinNo)
                            .addComponent(txtTinNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPagibigNo)
                            .addComponent(txtPagibigNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStatus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPosition)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblImmediateSup)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblBasicSalary))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtImmediateSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRiceSubsidy)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(txtRiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblPhoneAllowance, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblClothingAllowance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblgrossSemiMonthlyRate)
                                    .addComponent(txtGrossSemiMonthlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHourlyRate)
                                    .addComponent(txtHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseFrameClose(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseFrameClose
        this.dispose();
    }//GEN-LAST:event_btnCloseFrameClose

    private void GetEmployeeRecord(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_GetEmployeeRecord
        Employee _employee = new Employee();
        try {
            _employee = _employee.GetEmployeeRecords(EmployeeNo);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmViewEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
            /**txtEmployeeNo.setText(_employee.GetEmployeeNo());
            txtLastName.setText(_employee.GetLastName());
            txtFirstName.setText(_employee.GetFirstName());
            txtBirthday.setText(_employee.GetBirthday());
            txtAddress.setText(_employee.GetAddress());
            txtSSSNo.setText(_employee.GetSSSNo());
            txtPhealthNo.setText(_employee.GetPhealthNo());
            txtTinNo.setText(_employee.GetTinNo());
            txtPagibigNo.setText(_employee.GetPagibigNo());
            txtStatus.setText(_employee.GetStatus());
            txtPosition.setText(_employee.GetPosition());
            txtImmediateSup.setText(_employee.GetImmediateSup());
            txtBasicSalary.setText(_employee.GetBasicSalary());
            txtRiceSubsidy.setText(_employee.GetRiceSubsidy());
            txtPhoneAllowance.setText(_employee.GetPhoneAllowance());
            txtClothingAllowance.setText(_employee.GetClothingAllowance());
            txtGrossSemiMonthlyRate.setText(_employee.GetGrossSemiMonthlyRate());
            txtHourlyRate.setText(_employee.GetHourlyRate());
    }              
    }//GEN-LAST:event_GetEmployeeRecord

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                new FrmNewEmployee().setVisible(true);
            }
        });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBasicSalary;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblClothingAllowance;
    private javax.swing.JLabel lblEmployeeNo;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHourlyRate;
    private javax.swing.JLabel lblImmediateSup;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPagibigNo;
    private javax.swing.JLabel lblPhealthNo;
    private javax.swing.JLabel lblPhoneAllowance;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblRiceSubsidy;
    private javax.swing.JLabel lblSSSNo;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTinNo;
    private javax.swing.JLabel lblgrossSemiMonthlyRate;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBasicSalary;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtClothingAllowance;
    private javax.swing.JTextField txtEmployeeNo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGrossSemiMonthlyRate;
    private javax.swing.JTextField txtHourlyRate;
    private javax.swing.JTextField txtImmediateSup;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPagibigNo;
    private javax.swing.JTextField txtPhealthNo;
    private javax.swing.JTextField txtPhoneAllowance;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtRiceSubsidy;
    private javax.swing.JTextField txtSSSNo;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTinNo;
    // End of variables declaration//GEN-END:variables
}
