/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import classes.EmployeeAttendance;
import com.opencsv.exceptions.CsvValidationException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author DREAM PC
 */
public class FrmViewPayroll extends javax.swing.JDialog {

    /**
     * Creates new form FrmViewEmployee
     */
    
    public FrmViewPayroll(String EmployeeNo, String LastName, String FirstName) {
        setModalityType(ModalityType.APPLICATION_MODAL);
        initComponents(); //important that this will be declared first to enable lines of code after
        txtEmployeeNo.setText(EmployeeNo);
        txtLastName.setText(LastName);
        txtFirstName.setText(FirstName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmployeeNo = new javax.swing.JLabel();
        txtEmployeeNo = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblMonth = new javax.swing.JLabel();
        cmbMonth = new javax.swing.JComboBox<>();
        btnViewAttendance = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployeeAttendance = new javax.swing.JTable();
        lblTotalHoursWorked = new javax.swing.JLabel();
        txtTotalHoursWorked = new javax.swing.JTextField();
        lblGrossMonthlySalary = new javax.swing.JLabel();
        txtGrossMonthlySalary = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        lblHrs = new javax.swing.JLabel();
        lblPesos = new javax.swing.JLabel();
        lblNetMonthlySalary = new javax.swing.JLabel();
        txtNetMonthlySalary = new javax.swing.JTextField();
        lblPesos1 = new javax.swing.JLabel();
        lblBreakdownofDeductions = new javax.swing.JLabel();
        lblSSSDeduction = new javax.swing.JLabel();
        lblPhealthDeduction = new javax.swing.JLabel();
        lblPagibigDeduction = new javax.swing.JLabel();
        lblTotalDeduction = new javax.swing.JLabel();
        lblTaxableIncome = new javax.swing.JLabel();
        lblWithholdingTax = new javax.swing.JLabel();
        txtSSSDeduction = new javax.swing.JTextField();
        txtPhealthDeduction = new javax.swing.JTextField();
        txtPagibigDeduction = new javax.swing.JTextField();
        txtTotalDeduction = new javax.swing.JTextField();
        txtTaxableIncome = new javax.swing.JTextField();
        txtWithholdingTax = new javax.swing.JTextField();
        lblPesos2 = new javax.swing.JLabel();
        lblPesos3 = new javax.swing.JLabel();
        lblPesos4 = new javax.swing.JLabel();
        lblPesos5 = new javax.swing.JLabel();
        lblPesos6 = new javax.swing.JLabel();
        lblPesos7 = new javax.swing.JLabel();
        lblTotalAllowance = new javax.swing.JLabel();
        txtTotalAllowance = new javax.swing.JTextField();
        lblPesos8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                ClearTable(evt);
            }
        });

        lblEmployeeNo.setText("Employee No.:");

        txtEmployeeNo.setEditable(false);

        lblLastName.setText("Last Name:");

        txtLastName.setEditable(false);

        lblFirstName.setText("First Name:");

        txtFirstName.setEditable(false);

        lblMonth.setText("Month:");

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "September", "October", "November", "December" }));

        btnViewAttendance.setText("View Attendance");
        btnViewAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoadEmployeeAttendance(evt);
            }
        });

        tblEmployeeAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEmployeeAttendance);

        lblTotalHoursWorked.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalHoursWorked.setText("Total Hours Worked:");

        txtTotalHoursWorked.setEditable(false);
        txtTotalHoursWorked.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        lblGrossMonthlySalary.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGrossMonthlySalary.setText("Gross Monthly Salary:");

        txtGrossMonthlySalary.setEditable(false);
        txtGrossMonthlySalary.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        btnClose.setText("Close");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closewindow(evt);
            }
        });

        lblHrs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHrs.setText("Hrs");

        lblPesos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPesos.setText("Pesos");

        lblNetMonthlySalary.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNetMonthlySalary.setText("Net Monthly Salary:");

        txtNetMonthlySalary.setEditable(false);
        txtNetMonthlySalary.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        lblPesos1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPesos1.setText("Pesos");

        lblBreakdownofDeductions.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblBreakdownofDeductions.setText("Breakdown of Deductions");

        lblSSSDeduction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSSSDeduction.setText("SSS Deduction:");

        lblPhealthDeduction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhealthDeduction.setText("Philhealth Deduction:");

        lblPagibigDeduction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPagibigDeduction.setText("Pagibig Deduction:");

        lblTotalDeduction.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalDeduction.setText("Total Deduction:");

        lblTaxableIncome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTaxableIncome.setText("Taxable Income:");

        lblWithholdingTax.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWithholdingTax.setText("Withholding Tax:");

        txtSSSDeduction.setEditable(false);
        txtSSSDeduction.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtPhealthDeduction.setEditable(false);
        txtPhealthDeduction.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtPagibigDeduction.setEditable(false);
        txtPagibigDeduction.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtTotalDeduction.setEditable(false);
        txtTotalDeduction.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        txtTaxableIncome.setEditable(false);
        txtTaxableIncome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        txtWithholdingTax.setEditable(false);
        txtWithholdingTax.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        lblPesos2.setText("Pesos");

        lblPesos3.setText("Pesos");

        lblPesos4.setText("Pesos");

        lblPesos5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPesos5.setText("Pesos");

        lblPesos6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPesos6.setText("Pesos");

        lblPesos7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPesos7.setText("Pesos");

        lblTotalAllowance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalAllowance.setText("Total Allowance:");

        txtTotalAllowance.setEditable(false);
        txtTotalAllowance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        lblPesos8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPesos8.setText("Pesos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmployeeNo)
                                    .addComponent(lblLastName)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblMonth))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnViewAttendance)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtEmployeeNo)
                                                .addComponent(txtLastName)
                                                .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                                        .addGap(72, 72, 72)
                                        .addComponent(lblNetMonthlySalary)
                                        .addGap(35, 35, 35)
                                        .addComponent(txtNetMonthlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPesos1)))))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTotalDeduction)
                                            .addComponent(lblTaxableIncome))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTaxableIncome)
                                            .addComponent(txtTotalDeduction)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblWithholdingTax)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtWithholdingTax))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSSSDeduction)
                                            .addComponent(lblPhealthDeduction)
                                            .addComponent(lblPagibigDeduction))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSSSDeduction)
                                            .addComponent(txtPhealthDeduction)
                                            .addComponent(txtPagibigDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPesos2)
                                            .addComponent(lblPesos3)
                                            .addComponent(lblPesos4))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPesos5)
                                    .addComponent(lblPesos6)
                                    .addComponent(lblPesos7)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBreakdownofDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblGrossMonthlySalary)
                                            .addComponent(lblTotalHoursWorked)
                                            .addComponent(lblTotalAllowance))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtTotalHoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblHrs))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtTotalAllowance, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtGrossMonthlySalary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblPesos)
                                                    .addComponent(lblPesos8))))))))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeNo)
                    .addComponent(txtEmployeeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNetMonthlySalary)
                                .addComponent(txtNetMonthlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPesos1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMonth)
                            .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalHoursWorked)
                            .addComponent(txtTotalHoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHrs))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrossMonthlySalary)
                            .addComponent(txtGrossMonthlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPesos))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalAllowance)
                            .addComponent(txtTotalAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblPesos8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnViewAttendance)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBreakdownofDeductions)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSSSDeduction)
                            .addComponent(txtSSSDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPesos2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhealthDeduction)
                            .addComponent(txtPhealthDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPesos3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPagibigDeduction)
                            .addComponent(txtPagibigDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPesos4))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalDeduction)
                            .addComponent(txtTotalDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPesos5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTaxableIncome)
                                    .addComponent(txtTaxableIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWithholdingTax)
                                    .addComponent(txtWithholdingTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblPesos6)
                                .addGap(26, 26, 26)
                                .addComponent(lblPesos7))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Event Handler Method for View Attendance Button
    private void LoadEmployeeAttendance(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoadEmployeeAttendance
        EmployeeAttendance _attendance = new EmployeeAttendance();
        try {
            tblEmployeeAttendance.setModel(_attendance.GetEmployeeAttendance(txtEmployeeNo.getText(), cmbMonth.getSelectedItem().toString()));
            txtTotalHoursWorked.setText(String.valueOf(_attendance.GetTotalHours()));
            txtGrossMonthlySalary.setText(String.valueOf(_attendance.GetPayrollSalary()));
            txtNetMonthlySalary.setText(String.valueOf(_attendance.GetNetMonthlySalary()));
            txtSSSDeduction.setText(String.valueOf(_attendance.GetSSSDeduction()));
            txtPhealthDeduction.setText(String.valueOf(_attendance.GetPhealthDeduction()));
            txtPagibigDeduction.setText(String.valueOf(_attendance.GetPagibigDeduction()));
            txtTotalDeduction.setText(String.valueOf(_attendance.GetTotalDeduction()));
            txtTaxableIncome.setText(String.valueOf(_attendance.GetTaxableIncome()));
            txtWithholdingTax.setText(String.valueOf(_attendance.GetWithholdingTax()));
            txtTotalAllowance.setText(String.valueOf(_attendance.GetTotalAllowance()));
 
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmViewPayroll.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LoadEmployeeAttendance

    //Event Handler Method for Close Button
    private void closewindow(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closewindow
        this.dispose();
    }//GEN-LAST:event_closewindow

    //Event Handler Method for clearing the table when opening the View Employee Frame
    private void ClearTable(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ClearTable
        tblEmployeeAttendance.setModel(new DefaultTableModel());
    }//GEN-LAST:event_ClearTable


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnViewAttendance;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBreakdownofDeductions;
    private javax.swing.JLabel lblEmployeeNo;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGrossMonthlySalary;
    private javax.swing.JLabel lblHrs;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblNetMonthlySalary;
    private javax.swing.JLabel lblPagibigDeduction;
    private javax.swing.JLabel lblPesos;
    private javax.swing.JLabel lblPesos1;
    private javax.swing.JLabel lblPesos2;
    private javax.swing.JLabel lblPesos3;
    private javax.swing.JLabel lblPesos4;
    private javax.swing.JLabel lblPesos5;
    private javax.swing.JLabel lblPesos6;
    private javax.swing.JLabel lblPesos7;
    private javax.swing.JLabel lblPesos8;
    private javax.swing.JLabel lblPhealthDeduction;
    private javax.swing.JLabel lblSSSDeduction;
    private javax.swing.JLabel lblTaxableIncome;
    private javax.swing.JLabel lblTotalAllowance;
    private javax.swing.JLabel lblTotalDeduction;
    private javax.swing.JLabel lblTotalHoursWorked;
    private javax.swing.JLabel lblWithholdingTax;
    private javax.swing.JTable tblEmployeeAttendance;
    private javax.swing.JTextField txtEmployeeNo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGrossMonthlySalary;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNetMonthlySalary;
    private javax.swing.JTextField txtPagibigDeduction;
    private javax.swing.JTextField txtPhealthDeduction;
    private javax.swing.JTextField txtSSSDeduction;
    private javax.swing.JTextField txtTaxableIncome;
    private javax.swing.JTextField txtTotalAllowance;
    private javax.swing.JTextField txtTotalDeduction;
    private javax.swing.JTextField txtTotalHoursWorked;
    private javax.swing.JTextField txtWithholdingTax;
    // End of variables declaration//GEN-END:variables
}
